### ISSUE TITLE
This one seems not work .

### ISSUE THREAD

**Issue by intijk** [RyanMarcus/dirty-json#10]
I have such a json:
```
{
   "some": [a,b,c,],
   "b": a
}
```
but it doesn't convert to 
```
{
   "some": ["a","b","c"],
   "b": "a"
}
```

**Comment by RyanMarcus** [comment]
I can confirm this doesn't currently work. In fact, this doesn't work either:
```
{"some": [a,b,c,]}
```

I'll take a look today and see if I can figure it out.

**Comment by RyanMarcus** [comment]
I believe the current NPM version, `0.5.3`, will correctly parse the example.

**Comment by intijk** [comment]
You sure you mean `new NPM version 0.5.3`?
That is way too old.

https://github.com/npm/npm/releases
https://nodejs.org/en/download/releases/

**Comment by RyanMarcus** [comment]
Oh, sorry. I mean the new version of the package I just published on NPM.

**Comment by intijk** [comment]
:smiley: i get it , thank you
