### ISSUE TITLE
Error in webpack bundle

### ISSUE THREAD

**Issue by marcelinhov2** [RyanMarcus/dirty-json#12]
Hi man, nice project!!!

I'm trying to use it with webpack and it breaks my bundle with this error:
![image](https://user-images.githubusercontent.com/232648/37406187-5328f364-2775-11e8-8faa-4163288c7474.png)

Can you help me with this?

Tks!

**Comment by RyanMarcus** [comment]
The new API does not use Q. I believe this should fix the issue, but I haven't tried webpack. Can you give me a reproducer?
