### ISSUE TITLE
Handling duplicate keys with different strategy

### ISSUE THREAD

**Issue by RezaRahmati** [RyanMarcus/dirty-json#19]
Hi

I have a string like this 

```
   { 
    prop1: 'val1', 
    prop2: { 
         prop3: 'val3' , 
         messages: {something:'val'},  
         messages: { something:'val2', x : {x : 1, y : 5} } 
    } 
    , prop4: 'val4' 
 }
```

As it's obvious `messages` is duplicate and when I try to use the library it takes the last one, which is good for most cases.

I was wondering if it's possible to have an option how to treat duplicates, possible values could be (TakeLast, TakeFirst, ConvertToArray)

For `ConvertToArray`, the output will be something like below

```
  { 
    prop1: 'val1', 
    prop2: { 
         prop3: 'val3' , 
         messages:  [ 
                    {something:'val'},  
                    { something:'val2', x : {x : 1, y : 5} } 
         ] 
    } 
    , prop4: 'val4' 
 }
```

**Comment by RyanMarcus** [comment]
This is a little funky, because there are a lot of cases where a key could be overridden... for example, what if the overridden value is already a list?

The "solution" I came up with was to add a config option to build a sort of linked list out of duplicate keys.

```
parse('{"key": 1, "key": 2, "key": [1, 2, 3]}', {"duplicateKeys": true})
```
Will give:
```
{ key: { value: { value: 1, next: 2 }, next: [ 1, 2, 3 ] } }
```
