### ISSUE TITLE
Array of single object has error

### ISSUE THREAD

**Issue by gopalganu** [RyanMarcus/dirty-json#2]
{
"key" :  [{"a":"b"}]
}

This JSON above has an error, it doesn't seem to like an array of single object.

It works after adding a second object in the array
{
"key" :  [{"a":"b"}, {"c":"d"}]
}

**Comment by RyanMarcus** [comment]
I've confirmed this. Yikes! Since that's valid JSON, this is a pretty nasty bug. I'll take a look today...

Thanks for the report. I can't believe I missed this case!

**Comment by RyanMarcus** [comment]
I've fixed this and added tests. The changes are available on NPM in version `0.3.1`.

**Comment by gopalganu** [comment]
That worked. I think I found another one. Will report it as a separate issue. Appreciate the quick fix.
