### ISSUE TITLE
Handle empty values 

### ISSUE THREAD

**Issue by maxkoshevoi** [RyanMarcus/dirty-json#30]
For example, add `null` as a value if there is none.

`{ "key": }` -> `{ "key": null }`

**Comment by maxkoshevoi** [comment]
Sooo, this won't be implemented?

**Comment by RyanMarcus** [comment]
Sorry, I don't know why GitHub didn't add a comment from my commit. This is now fixed. :) Thanks for reporting the issue.

**Comment by maxkoshevoi** [comment]
That's awesome, thank you!
