### ISSUE TITLE
AGPL License - Force Open Source

### ISSUE THREAD

**Issue by tamusjroyce** [RyanMarcus/dirty-json#38]
You should mention at the top that by using this software, your program must also be open sourced to the AGPL specifications.
You should also include an additional option for a license available upon purchase. Unless this is agpl because of dependencies. Then this is purely academic. AGPL is not free. The cost is open sourcing anything that links to it. License trolls know this. I would remove that logo as well.

**Comment by RyanMarcus** [comment]
I have a large AGPL logo at the top of the README -- but I suppose that won't render if you are viewing the document in a text editor. I'll add a human-readable note. 

If anyone would like to inquire about alternative licenses, please reach out to me: ryanmarcus@csail.mit.edu
