### ISSUE TITLE
Use dirty-json without npm

### ISSUE THREAD

**Issue by ilyakatz** [RyanMarcus/dirty-json#5]
I have an environment where I cannot easily use npm, is there a way to use your library without it?

**Comment by RyanMarcus** [comment]
You could try using [the `bundle.js`](https://github.com/RyanMarcus/dirty-json/blob/gh-pages/assets/bundle.js) I created for the web demo, or you could use a tool like [Browserify](http://browserify.org/) to make your own bundled version of the library.

Sadly, I don't think I have time to maintain this package in any other form, i.e. bower or a single-file browser release. PRs welcome, though.
