### ISSUE TITLE
Parsing JSON fails on multidimensional array property

### ISSUE THREAD

**Issue by tphamZerion** [RyanMarcus/dirty-json#6]
When the server tried to parse an object contain a multidimensional array property, dirty-json sent out this message: 
> dirty-json got valid JSON that failed with the custom parser. We're returning the valid JSON, but please file a bug report here: https://github.com/RyanMarcus/dirty-json/issues

Here is my data: 
`{
  "rows": [["this", "is", "failing"]]
}`

 However, the parser works fine when the data has another array inside "rows" array.
Here is an example:
`{
  "rows": [["it", "works", "fine"], ["now"]]
}`

Let me know if you need more information about the issue

Thank you :)

**Comment by RyanMarcus** [comment]
Confirmed this. Thanks for the report. I'll try to fix it soon.

**Comment by RyanMarcus** [comment]
Think I have a fix. Turns out it was a pretty simple bug.

**Comment by tphamZerion** [comment]
Thank you

**Comment by RyanMarcus** [comment]
Fixed in 0.4.0. On NPM now.
